env:
  browser: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  # === ПРАВИЛА CI (исправленные) ===
  semi: ['error', 'never']                     # Без точек с запятой ✓
  brace-style: ['error', 'stroustrup']         # Скобки с новой строки ✓
  indent: ['error', 2]                         # Отступ 2 пробела ✓
  arrow-parens: ['error', 'always']            # ВСЕГДА скобки у параметров (исправлено!)

  # === кастомные правила ===
  no-console: 'off'
  import/extensions: 'off'
  no-trailing-spaces: 'error'
  arrow-body-style: 'off'
  consistent-return: 'off'
  no-param-reassign: ['error', { props: false }]
  import/no-unresolved: 'off'

settings:
  import/resolver:
    node:
      extensions: ['.js']
      moduleDirectory: ['node_modules', 'src/']

ignorePatterns:
  - dist/
  - node_modules/
  - '*.config.js'
  - '*.yml'
