env:
  browser: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  # ПРАВИЛА CI (обязательные)
  semi: ['error', 'never']
  brace-style: ['error', 'stroustrup']
  indent: ['error', 2]
  arrow-parens: ['error', 'as-needed']
  
  # Твои кастомные правила
  no-console: 'off'
  import/extensions: 'off'
  no-trailing-spaces: 'error'
  arrow-body-style: 'off'
  consistent-return: 'off'
  no-param-reassign: ['error', { props: false }]
  import/no-unresolved: 'off'

settings:
  import/resolver:
    node:
      extensions: ['.js']
      moduleDirectory: ['node_modules', 'src/']

ignorePatterns:
  - dist/
  - node_modules/
  - '*.config.js'
  - '*.yml'
